views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Plik zawierający funkcje renderowanych stron dostępnych bez zalogowania."""

# importy modułów py
import datetime
from flask import render_template, request, redirect, url_for, flash, Blueprint
from flask_login import current_user, login_required
from sqlalchemy import func, and_, or_


# importy nasze
from db_models import db, Grave, Parcel, Family, Messages, Obituaries

pages = Blueprint('pages', __name__)


@pages.route('/')
def index():
    """Renderowanie strony głównej."""
    messages_to_display = Messages.query.order_by(Messages.create_date.desc())
    return render_template('index.html', infos=messages_to_display)


@pages.route('/obituaries')
def obituaries():
    """Wyświatlanie nekrologów uporządkowane datami i tylko aktualne."""
    today_date = datetime.datetime.now() - datetime.timedelta(hours=4)
    obits = Obituaries.query.order_by(Obituaries.funeral_date.asc()).filter(
        Obituaries.funeral_date >= today_date)
    return render_template('obituaries.html', obits=obits)


@pages.route('/graves', methods=['GET'])
def graves():
    search_name = request.args.get('search_name')
    search_last_name = request.args.get('search_last_name')
    if current_user.is_authenticated:
        if not search_name and not search_last_name:
            #tworzy listę grobów
            graves_list = db.session.query(Grave.id, Grave.name, Grave.last_name, Grave.day_of_birth, Grave.day_of_death, Grave.parcel_id, Family.id.label("my_family"))\
                .outerjoin(Family, and_((Grave.id == Family.grave_id),(Family.user_id == current_user.id)))
        else:
            #wyszukiwarka
            search_like_name = '%'+search_name+'%'
            search_like_last_name = '%' + search_last_name + '%'
            graves_list = db.session.query(Grave.name, Grave.last_name, Grave.day_of_birth, Grave.day_of_death,Grave.parcel_id, Family.id.label("my_family"))\
                .outerjoin(Family, and_((Grave.id == Family.grave_id),(Family.user_id == current_user.id)))\
                .filter(and_(Grave.name.like(search_like_name), Grave.last_name.like(search_like_last_name)))
    else:
        if not search_name and not search_last_name:
            #tworzy listę grobów
            graves_list = db.session.query(Grave.id, Grave.name, Grave.last_name, Grave.day_of_birth, Grave.day_of_death, Grave.parcel_id)
        else:
            #wyszukiwarka
            search_like_name = '%'+search_name+'%'
            search_like_last_name = '%' + search_last_name + '%'
            graves_list = db.session.query(Grave.name, Grave.last_name, Grave.day_of_birth, Grave.day_of_death,Grave.parcel_id)\
                .filter(and_(Grave.name.like(search_like_name), Grave.last_name.like(search_like_last_name)))

    return render_template('graves.html', graves_list=graves_list, current_user=current_user)

@pages.route('/graves/<grave_id>/add-favourite', methods=['GET'])
@login_required
def add_favourite(grave_id):

    is_family = db.session.query(Family.user_id, Family.grave_id).\
        filter(Family.user_id == current_user.id, Family.grave_id == grave_id).first()
    if not is_family:
        new_favourite = Family(user_id=current_user.id,
                               grave_id=grave_id)
        db.session.add(new_favourite)
        db.session.commit()
        flash('Dodano do znanych grobów', 'succes')
    else:
        flash('Ten grób jest już w znanych grobach', 'error')

    return redirect('/graves')


@pages.route('/user/delete-favourite/<grave_id>', methods=['GET'])
@login_required
def delete_favourite(grave_id):
    back_url = request.args.get('back_url')
    my_favourite = Family.query.filter_by(user_id=current_user.id, grave_id=grave_id).first()
    if my_favourite:
        db.session.delete(my_favourite)
        db.session.commit()
    if back_url:
        return redirect(back_url)
    else:
        return redirect('/')


@pages.app_errorhandler(404)
def page_not_found(e):
    """Obsługa erroru 404."""
    return render_template('page_404.html')


@pages.app_errorhandler(405)
def page_wrong_method(e):
    """Obsługa erroru 405."""
    return redirect(url_for('pages.index'))

templates/add_grave.html
{% extends 'layout.html' %}
{% block head %}
<title>Cmentarz - panel użytkownika</title>
{% endblock %}
{% block body %}
{% from "_formhelpers.html" import render_field %}
<style>
.error {
color: #990000;
}
</style>

<h3>Podaj informacje dotyczące grobu: </h3>
<p>Wybrana parcela: {{ parcel.id }}</p>

<p>Cena: {{ parcel_type.price }}</p>


<form method="post">
    <div>{{ render_field(form.name, class="input_field") }}</div>
    <div>{{ render_field(form.surname, class="input_field") }}</div>
    <div>{{ render_field(form.birth_date, class="input_field") }}</div>
    <div>{{ render_field(form.death_date, class="input_field") }}</div>
    <button type="submit">Rezerwuj</button>
</form>

{% if error %}
<p class=error>{{ error }} </p>
{% endif %}
<br>

{% endblock %}

templates/flash_msg.html
{% for msg_type, div_id in [('succes', 'flash_message--succes'), ('error', 'flash_message--error')] %}
    {% with message = get_flashed_messages(category_filter = [msg_type])[0] %}
        {% if message %}
            <div class="flash_message {{ div_id }}">
                {{ message }}
            </div>
        {% endif %}
    {% endwith %}
{% endfor %}

templates/grave_page.html
{% extends 'layout.html' %}
{% block head %}
<title>Cmentarz - panel użytkownika</title>
{% endblock %}
{% block body %}
{% from "_formhelpers.html" import render_field %}
<style>
.error {
color: #990000;
}
</style>

<h4>Dane grobu:</h4>



Imię: {{ grave.name }}
<br>Nazwisko: {{ grave.last_name }}
<br>Parcela: {{ grave.parcel_id }}
<br>Data urodzenia: {{ grave.day_of_birth.strftime('%Y-%m-%d') }}
{% if grave.day_of_death %}
<br>Data śmierci: {{ grave.day_of_death.strftime('%Y-%m-%d') }}
{% endif %}
<br>Typ parceli: {{ parcel_type.description }}
<br>Cena: {{ parcel_type.price }}
<br>Opłacony do:



<br>
<h4>Edycja danych</h4>


<form method="post">
    <div>{{ render_field(form.name, class="input_field") }}</div>
    <div>{{ render_field(form.surname, class="input_field") }}</div>
    <div>{{ render_field(form.birth_date, class="input_field") }}</div>
    <div>{{ render_field(form.death_date, class="input_field") }}</div>
    <button type="submit">Zmień</button>
</form>


{% if error %}
<p class=error>{{ error }}</p>
{% endif %}
<br>

<form method="post" action="{{url_for('pages_user.delete_grave', grave_id=grave.id)}}">
    <button type="submit">Usuń grób</button>
</form>


{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block head %}
<title>Cmentarz - strona główna</title>
{% endblock %}
{% block body %}
{% include 'flash_msg.html' %}
<div class="info_on_main_page">
    <p>
        <h2> Witamy na stronie cmentarza XYZ!</h2>
    </p>
    <p>
        W naszym serwisie znajdą Państwo wszystkie informacje dotyczące naszego cmentarza.
        W celu wykorzystania wszystkich możliwości naszej strony proponujemy bardzo prostą
        rejestrację.
    </p>
    <p>
        W razie pytań lub jakichkolwiek wątpliwości prosimy o kontakt.
    </p>
</div>
<div class="info_on_main_page_news">
        <h2>Aktualności:</h2>
</div>
{% if infos %}
    {% for info in infos %}
<div class="info_on_main_page">
    {% if current_user.admin %}
    <a href="{{url_for('pages_admin.message_delete', message_id=info.id)}}">
        <img class="delete_icon" src="{{ url_for('static', filename='pictures/delete_icon.png') }}" alt="usuwanie">
    </a>
    <a href="{{url_for('pages_admin.message_edit', message_id=info.id)}}">
        <img class="edit_icon" src="{{ url_for('static', filename='pictures/edit-icon.png') }}" alt="edycja">
    </a>
    {% endif %}
    <h3> {{ info.title }}</h3>
    <p class="admin_msg">{{ info.content }}</p>
    <div class="small_txt_info">Data utworzenia: {{info.create_date.strftime('%Y-%m-%d %H:%M:%S')}}</div>
</div>
    {% endfor %}
{% endif %}
<div id="test"></div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Strona prywatna cmentarza xyz" />
    <meta name="keywords" content="śmierć, zgon, trumna, cmentarz, pogrzeb, grób, groby" />
    {% include 'include_styles.html' %}
    {% block head %}{% endblock %}
</head>
<body>
{% include 'navbar.html' %}
<div id="box">

    {% block body %}{% endblock %}
</div>
{% include 'include_scripts.html' %}
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block head %}
<title>Cmentarz - logowanie</title>
{% endblock %}
{% block body %}
{% include 'flash_msg.html' %}
    {% from "_formhelpers.html" import render_field %}
    <div id="login_box">
        <form method="post">
            <div class="input_category">Aby zalogować, podaj adres e-mail i hasło:</div>
            <div>{{ render_field(form_login.email_login, class="input_field") }}</div>
            <div>{{ render_field(form_login.password, class="input_field") }}</div>
            <br>
            <input class ="log_reg_button" type=submit value="Zaloguj">
            <a class="small_redirect_text" href="{{url_for('pages_log_sys.register')}}">Nie masz konta? Zarejestruj się!</a>
        </form>
        <a class="small_redirect_text" href="{{url_for('pages_log_sys.password_recovery')}}">Nie pamiętam hasła!</a>
    </div>
{% endblock %}

templates/message_delete.html
{% extends 'layout.html' %}
{% block head %}
<title>Panel Administratora</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admin.css') }}"/>
{% endblock %}
{% block body %}
{% include 'flash_msg.html' %}
<div id="new_post" class="admin_option_button"><span>Usuwanie wiadomości</span></div>
<div id="new_post_box" class="admin_option_box">
    <div class="warning">UWAGA: używasz właśnie opcji usuwania wiadomości, spowoduje to całkowite jej usunięcie, procesu tego nie będzie można cofnąć!</div>
    <form method="POST">
        <input class="text_input post_header" name="post_header" placeholder="Nagłówek" type="text" value="{{ message.title }}" disabled>
        <textarea class="text_input" name="post_content" placeholder="Tekst wiadomości" disabled>{{ message.content }}</textarea>
        <input class="send_data" type="submit" value="Usuń">
    </form>
</div>
{% endblock %}

templates/message_edit.html
{% extends 'layout.html' %}
{% block head %}
<title>Panel Administratora</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admin.css') }}"/>
{% endblock %}
{% block body %}
{% include 'flash_msg.html' %}
<div id="new_post" class="admin_option_button"><span>Edycja wiadomości</span></div>
<div id="new_post_box" class="admin_option_box">
    <form method="POST">
        <input class="text_input post_header" name="post_header" placeholder="Nagłówek" type="text" value="{{ message.title }}" required>
        <textarea class="text_input" name="post_content" placeholder="Tekst wiadomości" required>{{ message.content }}</textarea>
        <input class="send_data" type="submit" value="Edytuj">
    </form>
</div>
{% endblock %}

templates/navbar.html
<div id="navbar">
    <div id="up_bar"><div class="up_bar_txt">Cmentarz XYZ</div></div>
    <div id="btn_container">
        <div class="nav_button nav_button--left">
            <a href="{{url_for('pages.index')}}">Strona Główna</a>
        </div>
        <div class="nav_button nav_button--left">
            <a href="{{url_for('pages.obituaries')}}">Nekrologi</a>
        </div>
        <div class="nav_button nav_button--left">
            <a href="{{url_for('pages.graves')}}">Wyszukaj grób</a>
        </div>
        {% if current_user.is_authenticated %}
        <div class="nav_button nav_button--right">
            <a href="{{url_for('pages_log_sys.logout')}}">Wyloguj</a>
        </div>
        <div class="nav_button nav_button--right">
            <a class="nav_log_in_as" href="{{ url_for('pages_user.user_page') }}">
                Zalogowany jako:<br>
                {% if current_user.name and current_user.last_name %}
                    {{ current_user.name }} {{ current_user.last_name }}
                {% else %}
                    {{ current_user.email }}
                {% endif %}
            </a>
        </div>
        {% else %}
        <div class="nav_button nav_button--right">
            <a href="{{url_for('pages_log_sys.register')}}">Rejestruj</a>
        </div>
        <div class="nav_button nav_button--right">
            <a href="{{url_for('pages_log_sys.login')}}">Zaloguj</a>
        </div>
        {% endif %}
        <div style="clear: both"></div>
        {% if current_user.admin %}
        <div class="admin_panel nav_button"><a href="{{ url_for('pages_admin.admin') }}">Panel administratora</a></div>
        {% endif %}
    </div>
</div>

templates/obituaries.html
{% extends 'layout.html' %}
{% block head %}
<title>Panel Administratora</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/admin.css') }}"/>
{% endblock %}
{% block body %}
{% include 'flash_msg.html' %}
<p class="simple_txt">
<b>Umarłych wieczność dotąd trwa, dokąd pamięcią się im płaci.
Chwiejna waluta. Nie ma dnia, by ktoś wieczności swej nie tracił.</b>
Wisława Szymborska - "Rehabilitacja"
</p>
{% for obit in obits %}
<div class="outside_border">
    <div class="inside_border">
        {% if current_user.admin %}
        <a href="{{url_for('pages_admin.obituary_delete', obituary_id=obit.id)}}">
            <img class="delete_icon" src="{{ url_for('static', filename='pictures/delete_icon.png') }}" alt="usuwanie">
        </a>
        <a href="{{url_for('pages_admin.obituary_edit', obituary_id=obit.id)}}">
            <img class="edit_icon" src="{{ url_for('static', filename='pictures/edit-icon.png') }}" alt="edycja">
        </a>
        {% endif %}
        <div><img class="cross_icon" src="{{ url_for('static', filename='pictures/cross.png') }}" alt="krzyz"></div>
        <p>Z przykrością zawiadamiamy, że dnia {{obit.death_date.strftime('%Y-%m-%d')}}<br />
            {% if obit.gender == "man" %}Zmarł{% else %}Zmarła{% endif %} w wieku {{obit.years_old}} lat:</p>
        <p class="obituary_name">Ś.P. {{obit.name}} {{obit.surname}}</p>
        <p>Pogrzeb odbędzie się dnia {{obit.funeral_date.strftime('%Y-%m-%d')}} o godzinie {{obit.funeral_date.strftime('%H:%M')}}
            <br />w kościele przy cmentarzu XYZ</p>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/page_404.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Strona prywatna cmentarza xyz" />
    <meta name="keywords" content="śmierć, zgon, trumna, cmentarz, pogrzeb, grób, groby" />
    <meta http-equiv="Refresh" content="5;url={{url_for('pages.index')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/background.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/page_404.css') }}"/>
</head>
<body>
<div id="box">
    <br /><br /><br /><br /><br />
    <img src="{{ url_for('static', filename='pictures/tomb.png') }}">
    <div id="head_error">Błąd 404</div>
    <div id="msg_error">Nie znaleziono podanego adresu, za chwile zostaniesz przekierowany na stronę główną.</div>
    <img id="death" src="{{ url_for('static', filename='pictures/death_icon.png') }}">
</div>
</body>

templates/styles_to_include.html
<!-- nie jest uwzględniony page_404.css, jako zupełnie niezależna strona -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/form_box.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/background.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/flash_messages.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/navbar.css') }}"/>

templates/user_page.html
{% extends 'layout.html' %}
{% block head %}
<title>Cmentarz - panel użytkownika</title>
{% endblock %}
{% block body %}

{% include 'flash_msg.html' %}

<br>
<form method="post">
    <button type="submit" name="zombie_mode">TRYB ZOMBIE</button>
</form>

{% if zombie_mode %}
<p>Uwaga! Po zmroku zombie lubią się przechadzać po cmentarzu! Kliknij "Śledź zombie",
    by zobaczyć gdzie aktualnie przebywają.</p>


    <div class="follow_button">
        <form method="post">
    <button type="submit" name="follow_zombie">Śledź zombie</button>
            </form>
    </div>

<p>Sprawdź, czy ktoś ma dziś <a href="{{url_for('pages_user.zombie_deathday')}}"> zombie urodziny! </a></p>

{% endif %}
{% if not zombie_mode %}


<br>
<a href="{{ url_for('pages_user.user_set_pw') }}">Zmiana hasła</a>
<br>
<a href="{{ url_for('pages_user.user_set_data') }}">Zmiana danych personalnych</a>


<h3>Moje groby</h3>
{% if graves %}
    {% for grave in graves %}
    <ol>
        <a href="{{url_for('pages_user.grave', grave_id=grave.id)}}"> {{ grave.name }} {{ grave.last_name }}</a>
        (parcela: {{ grave.parcel_id }})
    </ol>
    {% endfor %}

{% endif %}

<h3>Znane groby</h3>

{% if favourite_graves_list %}

<table class="graves_table">
<tr>
    <th>Imię</th>
    <th>Nazwisko</th>
    <th>Data urodzenia</th>
    <th>Data śmierci</th>
    <th>Numer parceli</th>
    <th>Usuń</th>
</tr>


{% for favourite_grave in favourite_graves_list %}

    <tr>
        <td>{{ favourite_grave.name }}</td>
        <td>{{ favourite_grave.last_name }}</td>
        <td>{{ favourite_grave.day_of_birth }}</td>
        <td>{{ favourite_grave.day_of_death }}</td>
        <td>{{ favourite_grave.parcel_id }}</td>
        <td><a href="/user/delete-favourite/{{favourite_grave.id}}?back_url=/user">Usuń</a></td>
    </tr>
{% endfor %}

</table>

{% else %}
Nie masz znanych grobów

{% endif %}


<h3>Podgląd mapy cmentarza</h3>
<p>Wybierz wolną parcelę w celu rezerwacji grobu</p>

{% endif %}

<table width="700"  align="center" class="table">
    {% for j in range(1, max_p+1) %}
      <tr>
          {% for z in range(1, max_p+1) %}
            {% for parcel in parcels %}
                {% if parcel.position_x == j %}
                    {% if parcel.position_y == z %}
                        {% if parcel.id in taken_parcels %}
                        <th class="parcel_taken">
                            <div class="tooltip">
                                <div class="parcel_button">
                                    <a href="{{url_for('pages_user.add_grave', p_id=parcel.id)}}"> {{ parcel.id }} </a>
                                    <span class="tooltiptext"> Parcela zajęta </span>
                                </div>
                            </div>
                        </th>
                        {% else %}
                        <th class="parcel_free">
                            <div class="tooltip">
                                 <div class="parcel_button">
                                    <a href="{{url_for('pages_user.add_grave', p_id=parcel.id)}}"> {{ parcel.id }}  </a>
                                    <span class="tooltiptext"> Wybierz parcelę {{ parcel.id }} </span>
                                </div>
                            </div>
                        </th>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
          {% endfor %}
      </tr>
    {% endfor %}
</table>

{% if zombie_mode %}
<br>
<form method="post" action="{{url_for('pages_user.user_page')}}">
    <button type="submit" name="end">Zakończ tryb zombie</button>
</form>
{% endif %}

{% endblock %}

templates/user_settings.html
{% extends 'layout.html' %}

{% block head %}
{% if request.url_rule.endpoint == 'pages.register' %}
    <title>Cmentarz - rejestracja</title>
{% elif request.url_rule.endpoint == 'pages_user.user_set_pw' %}
    <title>Cmentarz - zmiana hasła</title>
{% elif request.url_rule.endpoint == 'pages_user.user_set_data' %}
    <title>Cmentarz - zmiana danych</title>
{% endif %}
{% endblock %}

{% block body %}
{% include 'flash_msg.html' %}
<div class="error_msg" id="error_testowy"></div>
{% from "_formhelpers.html" import render_field %}
<form method=post name="form_box" onsubmit="return validate()">
<div id="register_box">
{% if request.url_rule.endpoint == 'pages_log_sys.register' %}
<div class="input_category">Dane wymagane do rejestracji:</div>
    <br>
<!-- input do podania emaila -->
<div>{{ render_field(form_email.email, class="input_field") }}</div>
<div class="error_msg" id="email_field_error"></div>
<div class="succes_msg" id="email_field_succes"></div>
{% endif %}

{% if request.url_rule.endpoint == 'pages_user.user_set_pw' %}
<div class="input_category">Zmiana hasła:</div>
{% elif request.url_rule.endpoint == 'pages_user.user_set_data' %}
<div class="input_category">Zmiana danych osobowych:</div>
{% endif %}

{% if request.url_rule.endpoint in ['pages_user.user_set_data', 'pages_user.user_set_pw']  %}
<!-- stare hasło (aktualne) -->
<div>{{ render_field(form_oldpw.old_password, class="input_field") }}</div>
<div class="error_msg" id="old_pw_field_error"></div>
{% endif %}

{% if request.url_rule.endpoint in ['pages_log_sys.register', 'pages_user.user_set_pw', 'pages_log_sys.recovery_password']  %}
<!-- rejestracja uzytkownika/zmiana hasła, podanie hasła -->
<div>{{ render_field(form_pw.password, class="input_field") }}</div>
<div id="board"></div>
<!-- rejestracja uzytkownika/zmiana hasła, powtórz hasło -->
<div>{{ render_field(form_pw.repeat_password, class="input_field") }}</div>
<div class="error_msg" id="pw_field_error"></div>
{% endif %}

{% if request.url_rule.endpoint == 'pages.register' %}
<div class="input_category">Dane dodatkowe:</div>
{% endif %}

{% if request.url_rule.endpoint in ['pages_log_sys.register', 'pages_user.user_set_data']  %}
<div style="float: left">{{ render_field(form_data.name, class="input_field_1_2") }}</div>
<div style="float: left">{{ render_field(form_data.last_name, class="input_field_1_2") }}</div>
<div style="float: left">{{ render_field(form_data.city, class="input_field_3_4") }}</div>
<div style="float: left">{{ render_field(form_data.zip_code, class="input_field_1_4") }} <div class="error_msg" id="zip_code_field_error"></div></div>
<div style="clear: both">{{ render_field(form_data.street, class="input_field") }}</div>
<div style="float: left">{{ render_field(form_data.house_number, class="input_field_1_2") }}</div>
<div style="float: left">{{ render_field(form_data.flat_number, class="input_field_1_2") }}</div>
<div style="clear: both"></div>
{% endif %}

{% if request.url_rule.endpoint == 'pages_log_sys.register' %}
    <br>
<input class ="log_reg_button" type=submit value="Rejestruj">
<a class="small_redirect_text" href="{{url_for('pages_log_sys.login')}}">Masz już konto? Zaloguj się!</a>
{% endif %}

{% if request.url_rule.endpoint in ['pages_user.user_set_pw', 'pages_user.user_set_data', 'pages_log_sys.recovery_password'] %}
<input class ="log_reg_button" type=submit value="Zmień">
{% endif %}
{% if request.url_rule.endpoint in ['pages_user.user_set_pw', 'pages_user.user_set_data'] %}
<a class="small_redirect_text" href="{{url_for('pages_user.user_page')}}">Powrót bez wprowadzania zmian</a>
{% endif %}
</div>
</form>
{% endblock %}